server:
  port: 8761
eureka:
  instance:
    hostname: 165.232.104.233
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultUrl: http://${eureka.instance.hostname}:${server.port}/eureka/
