server:
  port: 8761
eureka:
  instance:
    hostname: 161.35.16.131
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultUrl: http://${eureka.instance.hostname}:${server.port}/eureka/
